plugins {
    id 'fabric-loom' version '1.2-SNAPSHOT'
}

version = "1.19.4"
group = "tisiry"

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    mavenCentral()
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
}
dependencies {
    minecraft "com.mojang:minecraft:1.19.4"

    mappings "net.fabricmc:yarn:1.19.4+build.2:v2"

    modImplementation "net.fabricmc:fabric-loader:0.14.21"

    modImplementation "net.fabricmc.fabric-api:fabric-api:0.87.0+1.19.4"

    modCompileOnly "com.terraformersmc:modmenu:4.1.2"
}



