plugins {
    id 'fabric-loom' version '1.1-SNAPSHOT'
}

version = "1.19.2"
group = "tisiry"

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    mavenCentral()
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.19.2"
    mappings "net.fabricmc:yarn:1.19.2+build.28:v2"
    modImplementation "net.fabricmc:fabric-loader:0.14.11"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.77.0+1.19.2"
    modCompileOnly "com.terraformersmc:modmenu:4.1.2"
}



